config/routes.rb
Rails.application.routes.draw do
  root to: 'companies#index'
  resources :companies
  resources :categories

  

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :company
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :companies, :through => :categorizations

  def to_s
    name
  end
  
end

app/models/company.rb
class Company < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged,:history]

  # def should_generate_new_friendly_id?
  #   new_record?
  # end
  
  has_many :categorizations
  has_many :categories, :through => :categorizations

  # searchable do 
  #   text :name, :boost => 5
  #   text :description
  # end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    # @search = Company.search do
    #   fulltext params[:search]
    # end
    # @companies = @search.results
    @companies = Company.all
  end

  def show
    @company = Company.friendly.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/index.html.erb
<!-- Jumbotron Banner Starts-->
<section class="content-section jumbotron-banner text-center">
  <div class="container-fluid">
    <div class="row">
      <div class = "jumbotron text-center" >
        <h1>MoonShot.in<small><sup>beta</sup></small></h1>
        <p>One Stop Solution for StartUp Funding</p>
      </div>
    </div>
  </div>
</section>
<!-- Jumbotron Banner Ends-->


 <!-- Categories Search Companies Dropdown Starts-->
<section>
  <div class="container-fluid category-filter">
    <div class="data-container col-md-8 col-md-offset-2 col-xs-10 col-xs-offset-1">
      
      <!-- <div class="row">
        <%= form_tag companies_path, :method => 'get', class: 'search-banner'  do %>
          <%= text_field_tag :search, params[:search], class: 'search-query form-control', placeholder: 'Search...' %>    
        <% end %>
      </div> -->

      <div class="row">
        <div class="search-banner">
          <input type="search" class="search-query form-control" placeholder="Search..." />
        </div>     
      </div>
      
      <div class="row">
        <div class="">
          <button class="btn btn-default dropdown-toggle " type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            Categories
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li class="disabled"><a href="#">Accelerator</li>
            <li class="disabled"><a href="#">Angel Syndicate</li>
            <li class="disabled"><a href="#">Co-Working Spaces</li>
            <li class="disabled"><a href="#">Crowd Funding Platforms</li>
            <li class="disabled"><a href="#">Government</li>
            <li class="disabled"><a href="#">Incubator</li>
            <li class="disabled"><a href="#">Individual Investors</li>
            <li class="disabled"><a href="#">Private Equity</li>
            <li class="disabled"><a href="#">Non Profit</li>
            <li><a href="#">Venture Capital</li>
          </ul>
        </div>
      </div>
      
      <!--<div class="row">
      <div class="total-companies text-center">
        <h4>100 Investors</h4>
      </div>     
    </div>-->
    
    </div>      
  </div>
</section>
<!-- Categories Search Companies Dropdown Ends -->

<!-- List Starts -->
<section>
  <div class="container-fluid data-list">
    <div class="data-container col-md-8 col-md-offset-2 col-xs-10 col-xs-offset-1">
      
      <div class="row">
        <div class="total-companies text-center">
          <h4>121 Investors</h4>
        </div>     
      </div>
      
      
      <div class="row">
        <div class="data-row">
        	<!-- <% @companies.each do |company| %>					
	          <h3><%= link_to company.name, company_path(company), class: 'company_name' %></h3>
	          <div class="intro-text"><%=company.description %></div>
	          <ul class="list-inline">
	            <li><i class="fa fa-university"></i> Venture Capital</li>
	            <li><i class="fa fa-map-marker"></i> Delhi · Mumbai · Bangalore</li>
	          </ul>
          <% end %> -->
          <h1>We're launching soon!!!</h1>  

        </div>
      </div>


      <!-- div class="row">
        <div class="data-row">
          <h3>Matrix Partners</h3>
          <div class="intro-text">Matrix Partners is a private equity investment firm focusing on venture capital investments in seed and early stage companies.
          </div>
          <ul class="list-inline">
            <li><i class="fa fa-university"></i> Venture Capital</li>
            <li><i class="fa fa-map-marker"></i> Delhi · Mumbai · Bangalore</li>              
          </ul>
        </div>
      </div> -->
    
    
    </div>      
  </div>
</section>
<!-- List Ends -->

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>

<p>
	Category:
	<% @company.categories.each do |category| %>
		<%= link_to category.name, category_path(category) %>
	<% end %>
</p>
<%= link_to "<< Back to Company List", companies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MoonShot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
	<script src="https://code.jquery.com/jquery.min.js"></script>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <style id="jsbin-css">
.jumbotron {
  
  border-radius: 0 !important;
  margin: 0px !important;
  background-color: #394258;
  color: white;
  

}

.navbar {
  
  margin: 0px !important;
  
}

.search-banner {
  
  background-color: #394258;
  padding: 0;
  margin: 10px 0 !important;
  height: 60px;
}

.search-query {
  
  border-radius: 0px;
  border: solid 0.3em;
  border-color: #394258;
  //padding: 20px 10px;
  font-size: 1.6rem;
  color: black;
  height: 60px;    
  
}
.content-section {
  
  padding: 0;
  margin: 0px !important;
  
  
}

.category-filter {
  
  background-color: #F7F7F7;
  padding: 20px 0;
  
}

#dropdownMenu1{
  
  border-radius: 0;
  
}

.total-companies{
  
  margin: 0px 0 !important;
  color: black;
  
}

.data-list {
  
  padding: 0px 0;
  background-color: #F7F7F7;
  
}

.data-container {
  
  //background-color: white;
  
}

.data-row {
  
  padding: 10px 30px;
  border: solid;
  border-width: 0 0 5px 0;
  border-color: #394258;
  background-color: white;
  
}

.img-center {
    margin: 0 auto;
}

</style>

</head>
<body>
	<nav class="navbar navbar-default navbar-static-top navbar-inverse">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/">MoonShot</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <!-- <ul class="nav navbar-nav">
	        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
	        <li><a href="#">Link</a></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><a href="#">Action</a></li>
	            <li><a href="#">Another action</a></li>
	            <li><a href="#">Something else here</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">Separated link</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">One more separated link</a></li>
	          </ul>
	        </li>
	      </ul>
	      <form class="navbar-form navbar-left" role="search">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Submit</button>
	      </form> -->
	      <ul class="nav navbar-nav navbar-right">
	        <li><%= link_to 'About', page_path('about') %></li>
	        <li><%= link_to 'Contact', page_path('contact') %></li>
	        <!-- <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><a href="#">Action</a></li>
	            <li><a href="#">Another action</a></li>
	            <li><a href="#">Something else here</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">Separated link</a></li>
	          </ul>
	        </li> -->
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

<%= yield %>
	<!-- Footer Starts-->
  
  <footer class="footer">
  	<div class="container">
      <div class="row">
          <div class="col-lg-12">
        		<hr>
            <p class="text-muted">Copyright &copy; MoonShot.in 2016</p>
          </div>
          <!-- /.col-lg-12 -->
      </div>
      <!-- /.row -->
    </div>
  </footer>

	<!-- Footer Ends -->
</body>
</html>

app/views/pages/about.html.erb
<!-- Jumbotron Banner Starts-->
<!-- <section class="content-section text-center">
  <div class="container-fluid">
    <div class="row">
      <div class = "jumbotron text-center" >
        <h1>About Us</h1>        
      </div>
    </div>
  </div>
</section> -->
<!-- Jumbotron Banner Ends-->


<!-- Introduction Row -->
<div class="container-fluid">	
	

  <section class="content-section jumbotron-banner text-center">
  <!-- <div class="container-fluid"> -->
    <div class="row">
      <div class = "jumbotron text-center" >
        <h1>About Us</h1>
        <p>It's Nice to Meet You!</p>
        <!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint, explicabo dolores ipsam aliquam inventore corrupti eveniet quisquam quod totam laudantium repudiandae obcaecati ea consectetur debitis velit facere nisi expedita vel?</p> -->
      </div>
    </div>
  <!-- </div> -->
  </section>


 	<!-- Team Members Row -->

  <div class="row">
      <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12">
          <h2 class="page-header">Meet our Team</h2>
      </div>
      <div class="col-lg-4 col-sm-6 text-center">
          <img class="img-circle img-responsive img-center" src="https://s16.postimg.io/mxk6rqqm9/gaurav.jpg" alt="Gaurav Modi">
          <h3>Gaurav Modi
              <br><small>Web Development and Analytics</small>
          </h3>
          <p><a href="https://www.linkedin.com/in/gaurav-modi" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
            <br>gaurav.modi@live.in<p>
          <!-- <p>What does this team member to? Keep it short! This is also a great spot for social links!</p> -->
      </div>
      <div class="col-lg-4 col-sm-6 text-center">
          <img class="img-circle img-responsive img-center" src="https://s16.postimg.org/3tqvbeds1/abhishek_kumar.jpg" alt="Abhishek Kumar">
          <h3>Abhishek Kumar
              <br><small>Product Development</small>
          </h3>
          <p><a href="https://www.linkedin.com/in/1988kumar" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
            <br>1988kumar@gmail.com<p>
          <!-- <p>What does this team member to? Keep it short! This is also a great spot for social links!</p> -->
      </div>
      <div class="col-lg-4 col-sm-6 text-center">
          <img class="img-circle img-responsive img-center" src="https://s16.postimg.org/5izyjgthd/shivam.jpg" alt="Shivam Tiwari">
          <h3>Shivam Tiwari
              <br><small>Product Development</small>
          </h3>
          <p><a href="https://in.linkedin.com/in/shivam-tiwari-92217639" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
            <br>shivam-tiwari@hotmail.com<p>
          <!-- <p>What does this team member to? Keep it short! This is also a great spot for social links!</p> -->
      </div>
  </div>
  <hr>
</div>

  

app/views/pages/contact.html.erb
<!-- Jumbotron Banner Starts-->
<section class="content-section jumbotron-banner text-center">
  <div class="container-fluid">
    <div class="row">
      <div class = "jumbotron text-center" >
        <h1>Contact Us</h1>
        <p>For any queries feel free to contact</p>
      </div>
    </div>
  </div>
</section>
<!-- Jumbotron Banner Ends-->

<div class="container">
<h3><u>Send a mail to us:</u></h3>
<strong><h4>Gaurav Modi: gaurav.modi@live.in<br><br>
Abhishek Kumar: 1988kumar@gmail.com</strong></h4>
</div>